[alias]
xtask = "run --package xtask --"
probe-rs = "run --package probe-rs-tools --bin probe-rs --features remote --"
smoke-tester = "test --package smoke_tester --"
target-gen = "run --package target-gen --release --"

[registries.nordic-artifactory]
index = "sparse+https://eu.files.nordicsemi.com/artifactory/api/cargo/cargo/index/"
